### PR TITLE
Create it cobang.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by hongquan** [comment]
Thank you, @albanobattistella . Please also help translate the .desktop file :-)

**Comment by albanobattistella** [comment]
👍😉
________________________________
Da: Nguyễn Hồng Quân <notifications@github.com>
Inviato: martedì 17 novembre 2020 09:52
A: hongquan/CoBang <CoBang@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [hongquan/CoBang] Create it cobang.po (#21)


Thank you, @albanobattistella<https://github.com/albanobattistella> . Please also help translate the .desktop file :-)

**Comment by hongquan** [comment]
The translation can be display if running from source. However I'm struggling with packaging, please be patient.

**Comment by albanobattistella** [comment]
> The translation can be display if running from source. However I'm struggling with packaging, please be patient.
Hi,
take your time!
Please, can you link to me the exact file I must to translate?Thanks!

**Comment by hongquan** [comment]
@albanobattistella   This file: https://github.com/hongquan/CoBang/blob/master/data/vn.hoabinh.quan.CoBang.desktop

**Pull request merged**
