### PR TITLE
Translation related patches 

### PR DESCRIPTION
**Pull request by sabriunal**
- Make desktop and appdata file translatable
- Create a pot file
- Update vi.po
- Update Turkish translation

### CODE REVIEW

**Comment by hongquan** [comment]
Thank you.

**Comment by hongquan** [comment]
Hi @sabriunal now I try to build Deb package with your change, and get this error:

```
[1/7] msgfmt ../po/it.po -o po/it/LC_MESSAGES/cobang.mo
[2/7] msgfmt ../po/nl.po -o po/nl/LC_MESSAGES/cobang.mo
[3/7] msgfmt ../po/fr.po -o po/fr/LC_MESSAGES/cobang.mo
[4/7] msgfmt ../po/tr.po -o po/tr/LC_MESSAGES/cobang.mo
[5/7] msgfmt ../po/vi.po -o po/vi/LC_MESSAGES/cobang.mo
[6/7] /usr/bin/meson --internal msgfmthelper ../data/vn.hoabinh.quan.CoBang.appdata.xml.in data/vn.hoabinh.quan.CoBang.appdata.xml xml ../data/../po
FAILED: data/vn.hoabinh.quan.CoBang.appdata.xml 
/usr/bin/meson --internal msgfmthelper ../data/vn.hoabinh.quan.CoBang.appdata.xml.in data/vn.hoabinh.quan.CoBang.appdata.xml xml ../data/../po
msgfmt: cannot read ../data/vn.hoabinh.quan.CoBang.appdata.xml.in: Premature end of data in tag component line 3

msgfmt: cannot read ../data/vn.hoabinh.quan.CoBang.appdata.xml.in: Premature end of data in tag component line 3

msgfmt: cannot locate ITS rules for ../data/vn.hoabinh.quan.CoBang.appdata.xml.in
[7/7] /usr/bin/meson --internal msgfmthelper ../data/vn.hoabinh.quan.CoBang.desktop.in data/vn.hoabinh.quan.CoBang.desktop desktop ../data/../po
ninja: build stopped: subcommand failed.
dh_auto_build: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 ninja -j12 -v returned exit code 1
make: *** [debian/rules:5: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

```

**Comment by hongquan** [comment]
Seems to need `appstream` as build dependency.

**Comment by sabriunal** [comment]
I've tested with flatpak and you need "appstreamcli"  due to the following changes. I can revert that part if you want.

https://github.com/hongquan/CoBang/pull/82/files#diff-ee0d750477d547a86d51c7a857402ca2dda7aed3d3f130978183d81ef204f9c2R37-R41

**Comment by hongquan** [comment]
Let's try to build with your change first. I install appstreamcli on Ubuntu but it still fails to locate ITS rules.

**Comment by hongquan** [comment]
I guess we need to rename the appdata file to metainfo.

**Comment by sabriunal** [comment]
okay.

**Comment by sabriunal** [comment]
> I guess we need to rename the appdata file to metainfo.



I spotted the problem and fixed via https://github.com/hongquan/CoBang/pull/86/files

**Pull request merged**
